#!/bin/bash
exec /usr/bin/meson setup \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --sbindir=/usr/bin \
  --buildtype=plain \
  --auto-features=enabled \
  --wrap-mode=nodownload \
  -D b_pie=true \
  "$@"
